from auto_strategy.BATTLE_FRONTINER_LV_UP import Farming_BATTLE_FRONTINER
from auto_strategy.Cerulean_City_FARMING import Farming_Cerulean_City
from auto_strategy.FALLARBOR_TOWN_FARMING import Farming_FALLARBOR_TOWN
from auto_strategy.Fuchsia_City_attack_EV import Farming_Fuchsia_City
from auto_strategy.Mistralton_City_FARMING import Farming_Mistralton_City
from auto_strategy.PETALBURG_CITY_FARMING import Farming_PETALBURG_CITY
from auto_strategy.SOOTOPOLIS_CITY_FARMING import Farming_SOOTOPOLIS_CITY
from auto_strategy.VERDANTURF_TOWN_FARMING import Farming_VERDANTURF_TOWN
